sudo: false
language: node_js
node_js:
  - "8"

cache:
  yarn: true
  pip: true
  directories:
    - "./node_modules
    - "./dist
    - "$HOME/.proselint"

stages:
  - smoke
  - build
  - post-build

jobs:
  include:
    - stage: lint
      name: Linting
      before_install:
        - npm install --global yarn
      install: yarn
      script: yarn lint

    - stage: build
      name: Build
      before_script:
        - source ./src/scripts/env.sh
      script: yarn build

    - stage: post-build
      name: Deploy
      if: branch = master
      script: bash ./src/scripts/deploy.sh

    - stage: post-build
      name: Link check
      allow_failures: true
      script: yarn linkcheck

    - stage: post-build
      name: Proselint
      language: python
      python:
        - 3.6
      allow_failures: true
      before_install:
        - pip install -r requirements.txt

      install:
        - pip install -r requirements.txt

      script:
        - cp .proselintrc ~/ && proselint src/content
