sudo: false
language: node_js
node_js:
  - "8"

cache:
  yarn: true
  directories:
    - node_modules
    - dist
    - .cache

stages:
  - lint
  - build
  - post-build

jobs:
  fast_finish: true
  allow_failures:
    - name: Link check

  include:
    - stage: lint
      name: Linting
      before_install: npm install --global yarn
      install: yarn
      script:
        - yarn lint:js
        - yarn lint:markdown
        - yarn lint:social

    - stage: build
      name: Build
      before_script: source ./src/scripts/env.sh
      script: yarn build

    - stage: post-build
      name: Deploy
      if: branch = master
      script: bash ./src/scripts/deploy.sh

    - stage: post-build
      name: Link check
      script: yarn linkcheck

    - stage: post-build
      name: Proselint
      language: python
      python: 3.6
      cache:
        pip: true
        directories:
          - dist
          - $HOME/.cache
      install: pip install -r requirements.txt
      script: cp .proselintrc ~/ && proselint src/content
