sudo: false
language: python
python:
  - "3.6"

sudo: false

cache:
  yarn: true
  pip: true
  directories:
    - $HOME/.proselint

stages:
  - lint
  - build
  - post-build

jobs:
  include:
    - stage: lint
      name: Linting
      before_install:
        - nvm use 8
        - npm install --global yarn
        - pip install -r requirements.txt
      install: yarn
      script: npm run lint
      cache:
        directories:
          - node_modules

    - stage: build
      name: Build
      before_script:
        - source ./src/scripts/env.sh
      script: npm run build
      cache:
        directories:
          - dist

    - stage: post-build
      name: Deploy
      if: branch = master
      script: bash ./src/scripts/deploy.sh

    - stage: post-build
      name: Link check
      script: npm run linkcheck
